# This is a basic workflow to help you get started with Actions

name: CI
on:
  push:
    paths:
      - env/**
      - modules/**
    branches:
      - main
  pull_request:
    paths:
      - env/**
      - modules/**
    branches:
      - main
  workflow_dispatch:
jobs:
  terraform:
    name: 'Dev Networking Terraform'
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: env/dev
    steps:
    - name: Checkout
      uses: actions/checkout@v2.5.0
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v2.0.3
      with:
        cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}
    - name: Terraform Format
      id: fmt
      run: terraform fmt -check -recursive
    - name: Terraform Init
      id: init
      run: terraform init
    - name: Terraform Plan
      id: plan
      if: github.event_name == 'pull_request'
      run: terraform plan
      continue-on-error: true
    - name: Terraform Plan Status
      if: steps.plan.outcome == 'failure'
      run: exit 1
    - name: Terraform Apply
      if: github.ref == 'refs/heads/master' && github.event_name == 'push'
      run: terraform apply -auto-approve
